### ISSUE TITLE
用户接取任务后创建订单 bug

### ISSUE THREAD

**Issue by zreren** [MetaBubble207/BWC#4]
提交后显示订单生成错误
但是确实产生了任务被用户接入的效果
![d42658537f72494f058a2d9a3d3a5ed](https://user-images.githubusercontent.com/70315161/184529504-87629e3a-4018-43b3-9a06-1a6194f4ea74.png)
![5ccced77701e5771b22311c5f6ce878](https://user-images.githubusercontent.com/70315161/184529507-d97b6fe2-b113-46fa-84ec-6122d7d277af.png)
![15cd59ea7c8992b0a85ef30a18af49c](https://user-images.githubusercontent.com/70315161/184529510-12c24880-1f73-46d4-addf-b1bff62c0003.png)
我接了1，2的任务，显示订单生成错误，但是首页只剩下3了

**Comment by leitianyu999** [comment]
目前看来是数据库数据问题，在修改后功能正常。
